language: python
python: 2.7
env:
- TOXENV=py27
- TOXENV=py33
- TOXENV=py34
- TOXENV=pypy
- TOXENV=py27-re2
before_install: >
  if [[ "$TOXENV" == *re2 ]]; then
     sudo add-apt-repository -y ppa:pi-rho/security;
     sudo apt-get update -q;
     sudo apt-get install -y libre2-dev;
  fi

install:
- pip install -U tox codecov

script: tox

after_success:
- codecov
